server:
  port: 8083
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.hello.entity



spring:
  main:
    lazy-initialization: true
  datasource:
      url: "jdbc:mysql://47.115.216.196:3306/circlefriends?useSSL=false&characterEncoding=UTF-8"
      username: "root"
      password: "hello123456"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        max-lifetime: 1800000
  redis:
    database: 0
    host: 47.115.216.196
    port: 6379
    password: hello123456

  mail:
    default-encoding: utf-8
    username: 1438679361@qq.com
    password: umxwrzkaxztegeif
    host: smtp.qq.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#图片上传地址，改为服务器可以访问和写入的文件夹 vue不允许使用本地绝对路径显示图片
upload:
  path: C:\Users\hechao\Desktop\aaa
