server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.demo.mybatis.entity



spring:
  datasource:
      url: "jdbc:mysql://47.115.216.196:3306/circlefriends?useSSL=false&characterEncoding=UTF-8"
      username: "root"
      password: "hello123456"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
  redis:
    database: 0
    host: 47.115.216.196
    port: 6379


